version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
